backend:
  name: git-gateway
  
  branch: main

media_folder: src/images
public_folder: /images

collections:
  - name: 'index'
    label: 'Index'
    folder: 'src/pages/'
    create: false
    fields:
      - { label: 'HeadingOne', name: 'headingOne', widget: 'string' }
      - { label: 'SubheadingOne', name: 'subheadingOne', widget: 'string' }
      - { label: 'HeroButtonCtaOne', name: 'heroButtonCtaOne', widget: 'string' }
      - { label: 'HeroButtonCtaTwo', name: 'heroButtonCtaTwo', widget: 'string' }
      - { label: 'HeadingTwo', name: 'headingTwo', widget: 'string' }
      - { label: 'HeadingThree', name: 'headingThree', widget: 'string' }
      - { label: 'HeadingFour', name: 'headingFour', widget: 'string' }
      - { label: 'HeroButtonLinkOne', name: 'heroButtonLinkOne', widget: 'string' }
      - { label: "Template Key", name: "templateKey", widget: "hidden", default: "main-pages"}
      - {
          label: Cards,
          name: cards,
          widget: list,
          fields:
            [
              { label: Title, name: title, widget: string },
              { label: Desc, name: desc, widget: string},
            ],
        }
      - {
          label: Dependancies,
          name: dependancies,
          widget: list,
          fields:
            [
              { label: Title, name: title, widget: string },
              { label: Desc, name: desc, widget: string},
            ],
        }
      - {
          label: Reviews,
          name: reviews,
          widget: list,
          fields:
            [
              { label: Name, name: name, widget: string },
              { label: Desc, name: desc, widget: string},
            ],
        }
    
  - name: 'about'
    label: 'About'
    folder: 'src/pages/about'
    create: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: "Template Key", name: "templateKey", widget: "hidden", default: "main-pages"}
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'services'
    label: 'Services'
    folder: 'src/pages/services'
    create: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: "Template Key", name: "templateKey", widget: "hidden", default: "main-pages"}
      - { label: 'Body', name: 'body', widget: 'markdown' } 
